apiVersion: openworld/v1alpha1
kind: ObservationSet
spec:
  observations:
  - id: o1
    type: sensor.a
    observedAt: "0000-01-01T00:00:01Z"
    values: {"v": 1}
  - id: o2
    type: sensor.a
    observedAt: "0000-02-29T00:00:02Z"
    values: {"v": 2}
