apiVersion: openworld/v1alpha1
kind: ObservationSet
spec:
  observations:
  - id: o1
    type: sensor.a
    observedAt: "2026-01-01T00:00:02Z"
    values: {"v": 1}
  - id: o2
    type: sensor.a
    observedAt: "2026-01-01T00:00:02Z"
    values: {"v": 1.0}
