"""Map the sample MES/QMS records in records/ to observations.yaml through the World's source bindings.

Each CSV is one record type of a source system declared in the World's interfaces/sources.yaml
(`spec.systems`). A row becomes one observation of type `<SYSTEM>.<record type>`; its subject is the record's
identifier, and its values are the remaining columns. When the World's ISA-95 binding maps the record type
(`spec.standardBindings.isa95.terms`), the observation records the ISA-95 object model in `values.isa95`.
The records are illustrative samples, not data from a real plant.

    python demos/business-ai/map_records.py           # write observations.yaml
    python demos/business-ai/map_records.py --check   # compare with the committed file
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

from ontle.yamlio import dump_yaml, load_yaml

HERE = Path(__file__).resolve().parent
SOURCES = HERE.parent.parent / "examples" / "business" / "manufacturing-quality-world" / "interfaces" / "sources.yaml"

# file -> (system, record type, identifier column); list-valued columns are separated by ';'
RECORDS = {
    "mes_production_lots.csv": ("MES", "production_lot", "lot_id"),
    "mes_equipment_events.csv": ("MES", "equipment", "equipment_id"),
    "qms_claims.csv": ("QMS", "claim", "claim_id"),
    "qms_nonconformances.csv": ("QMS", "nonconformance", "nc_id"),
    "qms_inspections.csv": ("QMS", "inspection", "lot_id"),
    "qms_capas.csv": ("QMS", "capa", "capa_id"),
}
LIST_COLUMNS = {"genealogy"}


def build() -> dict:
    sources = load_yaml(SOURCES.read_text(encoding="utf-8"))["spec"]
    isa95 = sources["standardBindings"]["isa95"]["terms"]
    observations = []
    for file, (system, record_type, id_column) in RECORDS.items():
        if record_type not in sources["systems"][system]:
            raise SystemExit(f"{system} declares no {record_type} records in {SOURCES.name}")
        with open(HERE / "records" / file, newline="", encoding="utf-8") as fh:
            for n, row in enumerate(csv.DictReader(fh), start=1):
                values = {k: (v.split(";") if k in LIST_COLUMNS else v)
                          for k, v in row.items() if k not in {id_column, "recorded_at"}}
                if record_type in isa95:
                    values["isa95"] = isa95[record_type]
                observations.append({
                    "id": f"{system.lower()}-{record_type.replace('_', '-')}-{n}",
                    "type": f"{system}.{record_type}",
                    "subject": row[id_column],
                    "observedAt": row["recorded_at"],
                    "values": values,
                })
    return {"apiVersion": "openworld/v1alpha1", "kind": "ObservationSet", "spec": {"observations": observations}}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    target = HERE / "observations.yaml"
    document = build()
    if parser.parse_args().check:
        if load_yaml(target.read_text(encoding="utf-8")) != document:
            raise SystemExit("observations.yaml differs from the mapped records")
        print("OK business-ai: observations.yaml matches the mapped records")
        return
    header = "# Generated by demos/business-ai/map_records.py from the sample records in records/.\n"
    target.write_text(header + dump_yaml(document, width=1000, default_flow_style=None), encoding="utf-8")
    print(f"wrote {len(document['spec']['observations'])} observations")


if __name__ == "__main__":
    main()
