"""Business AI demo: sample MES/QMS records through the manufacturing quality World into evidence.

1. observations.yaml (built by map_records.py through the World's ISA-95 binding) is compiled once a day by the
   quality-incident State Compiler; every EWS is checked against the output contract.
2. The adapter (models/adapter.yaml of the World Model: EWS -> structured_quality_model_input) keeps resolved
   values, unresolved alternatives (uncertainty), and the provenance of each field.
3. The model stub is a rule: an open leak finding without a verified CAPA is high claim-escalation risk, an
   open claim is medium, anything else is low. It is a stand-in, not a trained model.
4. Of the World Model's quality-basic@0.1.0 checks, traceability_to_lot is computed: the share of steps whose
   lot genealogy traces to an MES production-lot record. uncertainty_declared is not run, because the rule stub
   has no uncertainty model; the evidence says so. The result is a detached CompatibilityEvidence bound to the
   archive by digest.

    python demos/business-ai/run.py           # write expected-ews.yaml, evidence.yaml, the archive
    python demos/business-ai/run.py --check   # compare with the committed files
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from pipeline import REPO, compile_steps, finish, load  # noqa: E402

WORLD = REPO / "examples" / "business" / "manufacturing-quality-world"
WORLD_REF = "openworld-examples/manufacturing-quality-world@0.1.0"
MODEL = REPO / "examples" / "business" / "quality-transition-world-model"
COMPILER = "state/quality-incident-compiler.yaml"
STEPS = [f"2026-09-{day:02d}T18:00:00Z" for day in range(1, 11)]


def adapt(ews: dict) -> dict:
    spec = ews["spec"]
    return {"values": spec["state"], "alternatives": spec["unresolved"], "provenance": spec["provenance"]}


def escalation_risk(model_input: dict) -> dict:
    values = model_input["values"]
    inspections = values.get("inspection.results") or []
    capa = values.get("capa.status")
    if inspections and inspections[-1].endswith("_detected") and capa != "verified":
        risk = "high"
    elif values.get("claim.status") == "open":
        risk = "medium"
    else:
        risk = "low"
    return {"risk": risk}


def main() -> None:
    observations = load(HERE / "observations.yaml")
    steps = compile_steps(WORLD, COMPILER, observations, STEPS)
    predictions, traced = {}, 0
    for ews in steps:
        model_input = adapt(ews)
        prediction = escalation_risk(model_input)
        predictions[ews["spec"]["context"]["asOf"]] = prediction["risk"]
        lot_sources = model_input["provenance"].get("lot.genealogy") or []
        traced += bool(lot_sources) and all(o.startswith("mes-production-lot-") for o in lot_sources)

    evidence = {
        "apiVersion": "openworld/v1alpha1",
        "kind": "CompatibilityEvidence",
        "metadata": {
            "name": "claim-clm-001-rule-stub",
            "description": "Daily replay of the sample records for claim CLM-001 with a rule-based stub, not a trained model.",
        },
        "spec": {
            "subject": "openworld-examples/quality-transition-world-model@0.1.0",
            "subjectDigest": None,  # set from the archive by finish()
            "evaluationProfile": "quality-basic@0.1.0",
            "scope": {
                "worldRef": WORLD_REF,
                "worldView": f"{WORLD_REF}#views/quality-incident-task.yaml",
                "stateCompiler": f"{WORLD_REF}#{COMPILER}",
                "task": "claim_rca",
            },
            "result": {
                "status": "baseline",
                "model": "escalation_rule_stub",
                "steps": len(steps),
                "predictions": predictions,
                "metrics": {"traceability_to_lot": round(traced / len(steps), 4)},
                "checksNotRun": {"uncertainty_declared": "the rule stub has no uncertainty model"},
            },
        },
    }
    header = "# Generated by demos/business-ai/run.py. Checks of quality-basic@0.1.0 over a rule-based stub's predictions.\n"
    finish(HERE, MODEL, "quality-transition-world-model-0.1.0.owp.zip", steps[-1], evidence, header)


if __name__ == "__main__":
    main()
