apiVersion: openworld/v1alpha1
kind: ObservationSet
spec:
  observations:
  - id: o3
    type: sensor.b
    observedAt: "2026-01-01T00:00:01Z"
    values: {"v": "c"}
  - id: o1
    type: sensor.b
    observedAt: "2026-01-01T00:00:02Z"
    values: {"v": "a"}
  - id: o2
    type: sensor.b
    observedAt: "2026-01-01T00:00:01Z"
    values: {"v": "b"}
