"""Regenerate spec/rule-ids.yaml from the tables in spec/OWP_SPEC.md Appendix A.

    python scripts/sync_rule_ids.py

tests/test_rule_ids.py checks that the registry, the spec, the conformance suite, and both
implementations agree.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = """# Machine-readable list of OWP rule ids (spec Appendix A).
# Generated by scripts/sync_rule_ids.py; tests/test_rule_ids.py checks that the spec appendix,
# the conformance suite, and both implementations use exactly these ids.
apiVersion: openworld/v1alpha1
kind: RuleIdRegistry
"""


def rows(section: str):
    for line in section.splitlines():
        if line.startswith("| `"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            for rule in re.findall(r"`([a-z][a-z0-9.-]*)`", cells[0]):
                yield rule, cells[1], cells[2].replace("`", "")


def quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    spec = (ROOT / "spec" / "OWP_SPEC.md").read_text(encoding="utf-8")
    appendix = spec[spec.index("## Appendix A"):spec.index("## Appendix B")]
    split = appendix.index("| Warning id")
    lines = [f"  {r}: {{severity: error, section: {quote(s)}, summary: {quote(d)}}}" for r, s, d in rows(appendix[:split])]
    lines += [f"  {r}: {{severity: warning, section: {quote(s)}, summary: {quote(d)}}}" for r, s, d in rows(appendix[split:])]
    (ROOT / "spec" / "rule-ids.yaml").write_text(HEADER + "rules:\n" + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(lines)} rule ids")


if __name__ == "__main__":
    main()
