apiVersion: openworld/v1alpha1
kind: ObservationSet
spec:
  observations:
  - id: o9
    type: sensor.b
    observedAt: "2026-01-01T00:00:01Z"
    values: {"v": "nine"}
  - id: o10
    type: sensor.b
    observedAt: "2026-01-01T00:00:01Z"
    values: {"v": "ten"}
