"""Build observations.yaml from one episode of the pinned LeRobot dataset (needs network and pyarrow).

The World binds `datasets/manipulation-episodes.yaml` to hf://datasets/k-chan-l/lekiwi_pick_and_place2 at a
fixed commit. This script downloads that commit's metadata and first data file, takes episode 0, keeps one
frame per second, and writes an ObservationSet:

- `proprioception`: arm joint positions, gripper position, and measured base velocities (observation.state)
- `teleop.action`: the recorded teleoperation command at the same frame (action); no State Compiler binds it,
  the demo's evaluation compares predictions with it
- `language_task`: the episode's task string

observedAt is a fixed origin plus the episode timestamp, not wall-clock time. Values are rounded to 4 decimals.

    pip install pyarrow
    python demos/physical-ai/extract.py
"""
from __future__ import annotations

import io
import json
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

DATASET = "k-chan-l/lekiwi_pick_and_place2"
REVISION = "de33a7ae7c1769d042e1303894df3b7ea804de21"
BASE = f"https://huggingface.co/datasets/{DATASET}/resolve/{REVISION}/"
EPISODE = 0
FPS = 30
ORIGIN = datetime(2026, 1, 1, tzinfo=timezone.utc)
HERE = Path(__file__).resolve().parent


def fetch(path: str) -> bytes:
    with urllib.request.urlopen(BASE + path) as response:
        return response.read()


def at(second: int) -> str:
    return (ORIGIN + timedelta(seconds=second)).strftime("%Y-%m-%dT%H:%M:%SZ")


def rounded(values) -> list[float]:
    return [round(float(v), 4) + 0.0 for v in values]  # + 0.0 turns -0.0 into 0.0


def main() -> None:
    import pyarrow.parquet as pq

    from ontle.yamlio import dump_yaml

    info = json.loads(fetch("meta/info.json"))
    assert info["fps"] == FPS and info["codebase_version"] == "v3.0", info
    tasks = {r["task_index"]: r["task"] for r in pq.read_table(io.BytesIO(fetch("meta/tasks.parquet"))).to_pylist()}
    rows = [r for r in pq.read_table(io.BytesIO(fetch("data/chunk-000/file-000.parquet"))).to_pylist()
            if r["episode_index"] == EPISODE and r["frame_index"] % FPS == 0]

    observations = [{
        "id": f"ep{EPISODE:03d}-task",
        "type": "language_task",
        "observedAt": at(0),
        "values": {"text": tasks[rows[0]["task_index"]]},
    }]
    for row in rows:
        second = row["frame_index"] // FPS
        state, action = row["observation.state"], row["action"]
        observations.append({
            "id": f"ep{EPISODE:03d}-f{row['frame_index']:05d}-state",
            "type": "proprioception",
            "observedAt": at(second),
            "values": {"joint_state": rounded(state[0:5]), "gripper": round(float(state[5]), 4) + 0.0,
                       "base_velocity": rounded(state[6:9])},
        })
        observations.append({
            "id": f"ep{EPISODE:03d}-f{row['frame_index']:05d}-action",
            "type": "teleop.action",
            "observedAt": at(second),
            "values": {"arm": rounded(action[0:5]), "gripper": round(float(action[5]), 4) + 0.0,
                       "base_velocity": rounded(action[6:9])},
        })

    header = (
        f"# Episode {EPISODE} of hf://datasets/{DATASET} @ {REVISION} (Apache-2.0), one frame per second.\n"
        "# Generated by demos/physical-ai/extract.py; observedAt = 2026-01-01T00:00:00Z + episode timestamp.\n"
    )
    document = {"apiVersion": "openworld/v1alpha1", "kind": "ObservationSet", "spec": {"observations": observations}}
    (HERE / "observations.yaml").write_text(header + dump_yaml(document, width=1000, default_flow_style=None), encoding="utf-8")
    print(f"wrote {len(observations)} observations from {len(rows)} frames")


if __name__ == "__main__":
    main()
