"""Physical AI demo: one real LeKiwi episode through the mobile-manipulation World into evidence.

1. observations.yaml (built by extract.py from the pinned LeRobot dataset) is compiled once per second by the
   World's pick-place State Compiler; every EWS is checked against the output contract.
2. The adapter (models/adapter.yaml of the World Model: EWS -> multimodal_model_input) takes the arm joints,
   gripper, and instruction from the EWS state.
3. The model stub holds position: it commands the current arm and gripper positions and zero base velocity.
   It is a baseline, not a trained model.
4. Its commands are compared with the recorded teleoperation commands; the errors become a detached
   CompatibilityEvidence for multimodal-action-world-model, bound to the archive by digest.

    python demos/physical-ai/run.py           # write expected-ews.yaml, evidence.yaml, the archive
    python demos/physical-ai/run.py --check   # compare with the committed files
"""
from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from pipeline import REPO, compile_steps, finish, load, observations_at  # noqa: E402

WORLD = REPO / "examples" / "physical-ai" / "mobile-manipulation-world"
WORLD_REF = "openworld-examples/mobile-manipulation-world@0.1.0"
MODEL = REPO / "examples" / "physical-ai" / "multimodal-action-world-model"
COMPILER = "state/pick-place-compiler.yaml"
ORIGIN = datetime(2026, 1, 1, tzinfo=timezone.utc)
STEPS = [(ORIGIN + timedelta(seconds=s)).strftime("%Y-%m-%dT%H:%M:%SZ") for s in range(60)]


def adapt(ews: dict) -> dict | None:
    """EWS -> model input. Unresolved or missing required fields mean no input for this step."""
    state = ews["spec"]["state"]
    if "robot.joint_state" not in state or "robot.gripper_state" not in state:
        return None
    return {"joints": state["robot.joint_state"], "gripper": state["robot.gripper_state"],
            "instruction": state.get("task.instruction")}


def hold_position(model_input: dict) -> dict:
    return {"arm": model_input["joints"], "gripper": model_input["gripper"], "base_velocity": [0.0, 0.0, 0.0]}


def mean(values: list[float]) -> float | None:
    return round(sum(values) / len(values), 4) if values else None


def main() -> None:
    observations = load(HERE / "observations.yaml")
    episodes = compile_steps(WORLD, COMPILER, observations, STEPS)
    arm, gripper, base = [], [], []
    for ews in episodes:
        model_input = adapt(ews)
        recorded = observations_at(observations, "teleop.action", ews["spec"]["context"]["asOf"])
        if model_input is None or len(recorded) != 1:
            continue
        command, truth = hold_position(model_input), recorded[0]["values"]
        arm += [abs(p - t) for p, t in zip(command["arm"], truth["arm"])]
        gripper.append(abs(command["gripper"] - truth["gripper"]))
        base += [abs(p - t) for p, t in zip(command["base_velocity"], truth["base_velocity"])]

    evidence = {
        "apiVersion": "openworld/v1alpha1",
        "kind": "CompatibilityEvidence",
        "metadata": {
            "name": "lekiwi-episode-0-hold-position",
            "description": "Offline replay of episode 0 of hf://datasets/k-chan-l/lekiwi_pick_and_place2 "
                           "(de33a7ae7c1769d042e1303894df3b7ea804de21) with a hold-position stub, not a trained model.",
        },
        "spec": {
            "subject": "openworld-examples/multimodal-action-world-model@0.1.0",
            "subjectDigest": None,  # set from the archive by finish()
            "evaluationProfile": "offline-action-replay@0.1.0",
            "scope": {
                "worldRef": WORLD_REF,
                "worldView": f"{WORLD_REF}#views/pick-place-task.yaml",
                "stateCompiler": f"{WORLD_REF}#{COMPILER}",
                "environment": f"{WORLD_REF}#environment/reference-environment.yaml",
                "task": "pick_place",
            },
            "result": {
                "status": "baseline",
                "model": "hold_position_stub",
                "steps": len(gripper),
                "ewsMissing": sorted(episodes[-1]["spec"]["missing"]),
                "metrics": {"arm_position_mae": mean(arm), "gripper_position_mae": mean(gripper),
                            "base_velocity_mae": mean(base)},
            },
        },
    }
    header = "# Generated by demos/physical-ai/run.py. Metrics compare a hold-position stub with recorded teleoperation.\n"
    finish(HERE, MODEL, "multimodal-action-world-model-0.1.0.owp.zip", episodes[-1], evidence, header)


if __name__ == "__main__":
    main()
